### ISSUE TITLE
Failed due to Segmentation fault

### ISSUE THREAD

**Issue by yasaichi** [draftcode/extreme_timeout#5]
I faced the following error when I executed the code with irb in Red Hat Enterprise Linux 7: 

```ruby
irb(main):001:0> require 'extreme_timeout'; ExtremeTimeout::timeout(1) { sleep (2) }
```

```log
/usr/local/lib/ruby/2.1.0/irb/inspector.rb:122: [BUG] Segmentation fault at 0x00000000000018
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0019 p:0010 s:0070 e:000068 BLOCK  /usr/local/lib/ruby/2.1.0/irb/inspector.rb:122 [FINISH]
c:0018 p:---- s:0066 e:000065 CFUNC  :call
c:0017 p:0011 s:0062 e:000061 METHOD /usr/local/lib/ruby/2.1.0/irb/inspector.rb:115
c:0016 p:0012 s:0058 e:000057 METHOD /usr/local/lib/ruby/2.1.0/irb/context.rb:386
c:0015 p:0015 s:0055 e:000052 METHOD /usr/local/lib/ruby/2.1.0/irb.rb:662
c:0014 p:0035 s:0050 e:000049 BLOCK  /usr/local/lib/ruby/2.1.0/irb.rb:493
c:0013 p:0040 s:0042 e:000041 METHOD /usr/local/lib/ruby/2.1.0/irb.rb:624
c:0012 p:0009 s:0037 e:000036 BLOCK  /usr/local/lib/ruby/2.1.0/irb.rb:489
c:0011 p:0118 s:0033 e:000032 BLOCK  /usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:247 [FINISH]
c:0010 p:---- s:0030 e:000029 CFUNC  :loop
c:0009 p:0007 s:0027 e:000026 BLOCK  /usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:233 [FINISH]
c:0008 p:---- s:0025 e:000024 CFUNC  :catch
c:0007 p:0015 s:0021 e:000020 METHOD /usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:232
c:0006 p:0030 s:0018 E:000a48 METHOD /usr/local/lib/ruby/2.1.0/irb.rb:488
c:0005 p:0008 s:0015 e:000014 BLOCK  /usr/local/lib/ruby/2.1.0/irb.rb:397 [FINISH]
c:0004 p:---- s:0013 e:000012 CFUNC  :catch
c:0003 p:0143 s:0009 E:000e88 METHOD /usr/local/lib/ruby/2.1.0/irb.rb:396
c:0002 p:0021 s:0004 E:001e28 EVAL   /usr/local/bin/irb:11 [FINISH]
c:0001 p:0000 s:0002 E:0022b8 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/bin/irb:11:in `<main>'
/usr/local/lib/ruby/2.1.0/irb.rb:396:in `start'
/usr/local/lib/ruby/2.1.0/irb.rb:396:in `catch'
/usr/local/lib/ruby/2.1.0/irb.rb:397:in `block in start'
/usr/local/lib/ruby/2.1.0/irb.rb:488:in `eval_input'
/usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
/usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `catch'
/usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `loop'
/usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.1.0/irb.rb:489:in `block in eval_input'
/usr/local/lib/ruby/2.1.0/irb.rb:624:in `signal_status'
/usr/local/lib/ruby/2.1.0/irb.rb:493:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.1.0/irb.rb:662:in `output_value'
/usr/local/lib/ruby/2.1.0/irb/context.rb:386:in `inspect_last_value'
/usr/local/lib/ruby/2.1.0/irb/inspector.rb:115:in `inspect_value'
/usr/local/lib/ruby/2.1.0/irb/inspector.rb:115:in `call'
/usr/local/lib/ruby/2.1.0/irb/inspector.rb:122:in `block in <module:IRB>'

-- C level backtrace information -------------------------------------------
/usr/local/lib/libruby.so.2.1(+0x1e23ac) [0x7fad0b8a33ac] vm_dump.c:690
/usr/local/lib/libruby.so.2.1(+0x77713) [0x7fad0b738713] error.c:312
/usr/local/lib/libruby.so.2.1(rb_bug+0xb3) [0x7fad0b739363] error.c:339
/usr/local/lib/libruby.so.2.1(+0x15aa83) [0x7fad0b81ba83] signal.c:824
/lib64/libpthread.so.0(+0xf100) [0x7fad0b4b4100]
/usr/local/lib/libruby.so.2.1(+0x1cc1f9) [0x7fad0b88d1f9] vm_method.c:582
/usr/local/lib/libruby.so.2.1(+0x1cc4fe) [0x7fad0b88d4fe] vm_insnhelper.c:855
/usr/local/lib/libruby.so.2.1(+0x1d06e7) [0x7fad0b8916e7] insns.def:1024
/usr/local/lib/libruby.so.2.1(+0x1d42df) [0x7fad0b8952df] vm.c:1427
/usr/local/lib/libruby.so.2.1(+0x1d744a) [0x7fad0b89844a] vm.c:817
/usr/local/lib/libruby.so.2.1(+0x1d7c2b) [0x7fad0b898c2b] vm.c:881
/usr/local/lib/libruby.so.2.1(+0x1d7cda) [0x7fad0b898cda] vm.c:900
/usr/local/lib/libruby.so.2.1(+0x87760) [0x7fad0b748760] proc.c:724
/usr/local/lib/libruby.so.2.1(+0x1d92f1) [0x7fad0b89a2f1] vm_insnhelper.c:1510
/usr/local/lib/libruby.so.2.1(+0x1d06f4) [0x7fad0b8916f4] insns.def:1025
/usr/local/lib/libruby.so.2.1(+0x1d42df) [0x7fad0b8952df] vm.c:1427
/usr/local/lib/libruby.so.2.1(+0x1dbbf5) [0x7fad0b89cbf5] vm.c:817
/usr/local/lib/libruby.so.2.1(rb_rescue2+0xbe) [0x7fad0b74122e] eval.c:754
/usr/local/lib/libruby.so.2.1(+0x1ca26e) [0x7fad0b88b26e] vm_eval.c:1049
/usr/local/lib/libruby.so.2.1(+0x1d92f1) [0x7fad0b89a2f1] vm_insnhelper.c:1510
/usr/local/lib/libruby.so.2.1(+0x1d1035) [0x7fad0b892035] insns.def:996
/usr/local/lib/libruby.so.2.1(+0x1d42df) [0x7fad0b8952df] vm.c:1427
/usr/local/lib/libruby.so.2.1(+0x1dc709) [0x7fad0b89d709] vm.c:817
/usr/local/lib/libruby.so.2.1(+0x1cd8ba) [0x7fad0b88e8ba] vm_eval.c:1856
/usr/local/lib/libruby.so.2.1(rb_catch_obj+0xc) [0x7fad0b88e97c] vm_eval.c:1835
/usr/local/lib/libruby.so.2.1(+0x1cda1e) [0x7fad0b88ea1e] vm_eval.c:1821
/usr/local/lib/libruby.so.2.1(+0x1d92f1) [0x7fad0b89a2f1] vm_insnhelper.c:1510
/usr/local/lib/libruby.so.2.1(+0x1d1035) [0x7fad0b892035] insns.def:996
/usr/local/lib/libruby.so.2.1(+0x1d42df) [0x7fad0b8952df] vm.c:1427
/usr/local/lib/libruby.so.2.1(+0x1dc709) [0x7fad0b89d709] vm.c:817
/usr/local/lib/libruby.so.2.1(+0x1cd8ba) [0x7fad0b88e8ba] vm_eval.c:1856
/usr/local/lib/libruby.so.2.1(rb_catch_obj+0xc) [0x7fad0b88e97c] vm_eval.c:1835
/usr/local/lib/libruby.so.2.1(+0x1cda1e) [0x7fad0b88ea1e] vm_eval.c:1821
/usr/local/lib/libruby.so.2.1(+0x1d92f1) [0x7fad0b89a2f1] vm_insnhelper.c:1510
/usr/local/lib/libruby.so.2.1(+0x1d1035) [0x7fad0b892035] insns.def:996
/usr/local/lib/libruby.so.2.1(+0x1d42df) [0x7fad0b8952df] vm.c:1427
/usr/local/lib/libruby.so.2.1(rb_iseq_eval_main+0x1f6) [0x7fad0b89e076] vm.c:1666
/usr/local/lib/libruby.so.2.1(+0x7d8df) [0x7fad0b73e8df] eval.c:253
/usr/local/lib/libruby.so.2.1(ruby_exec_node+0x1d) [0x7fad0b7409fd] eval.c:318
/usr/local/lib/libruby.so.2.1(ruby_run_node+0x1c) [0x7fad0b7431cc] eval.c:310
irb() [0x40089b]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fad0a9c7b15]
irb() [0x4008c9]

-- Other runtime information -----------------------------------------------

* Loaded script: irb

* Loaded features:

    0 enumerator.so
    1 /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
    2 /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
    3 /usr/local/lib/ruby/2.1.0/x86_64-linux/rbconfig.rb
    4 thread.rb
    5 /usr/local/lib/ruby/2.1.0/x86_64-linux/thread.so
    6 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/compatibility.rb
    7 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/defaults.rb
    8 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/deprecate.rb
    9 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/errors.rb
   10 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/version.rb
   11 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/requirement.rb
   12 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/platform.rb
   13 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/basic_specification.rb
   14 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/stub_specification.rb
   15 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/util/list.rb
   16 /usr/local/lib/ruby/2.1.0/x86_64-linux/stringio.so
   17 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb
   18 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/exceptions.rb
   19 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
   20 /usr/local/lib/ruby/2.1.0/monitor.rb
   21 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb
   22 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems.rb
   23 /usr/local/lib/ruby/2.1.0/e2mmap.rb
   24 /usr/local/lib/ruby/2.1.0/irb/init.rb
   25 /usr/local/lib/ruby/2.1.0/irb/workspace.rb
   26 /usr/local/lib/ruby/2.1.0/irb/inspector.rb
   27 /usr/local/lib/ruby/2.1.0/irb/context.rb
   28 /usr/local/lib/ruby/2.1.0/irb/extend-command.rb
   29 /usr/local/lib/ruby/2.1.0/irb/output-method.rb
   30 /usr/local/lib/ruby/2.1.0/irb/notifier.rb
   31 /usr/local/lib/ruby/2.1.0/irb/slex.rb
   32 /usr/local/lib/ruby/2.1.0/irb/ruby-token.rb
   33 /usr/local/lib/ruby/2.1.0/irb/ruby-lex.rb
   34 /usr/local/lib/ruby/2.1.0/irb/src_encoding.rb
   35 /usr/local/lib/ruby/2.1.0/irb/magic-file.rb
   36 /usr/local/lib/ruby/2.1.0/x86_64-linux/readline.so
   37 /usr/local/lib/ruby/2.1.0/irb/input-method.rb
   38 /usr/local/lib/ruby/2.1.0/irb/locale.rb
   39 /usr/local/lib/ruby/2.1.0/irb.rb
   40 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/path_support.rb
   41 /usr/local/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb
   42 /usr/local/lib/ruby/gems/2.1.0/gems/extreme_timeout-0.3.1/lib/extreme_timeout.so

* Process memory map:

00400000-00401000 r-xp 00000000 ca:02 358585                             /usr/local/bin/ruby
00600000-00601000 r--p 00000000 ca:02 358585                             /usr/local/bin/ruby
00601000-00602000 rw-p 00001000 ca:02 358585                             /usr/local/bin/ruby
0083b000-00f09000 rw-p 00000000 00:00 0                                  [heap]
7fad02dad000-7fad02dc2000 r-xp 00000000 ca:02 16818313                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fad02dc2000-7fad02fc1000 ---p 00015000 ca:02 16818313                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fad02fc1000-7fad02fc2000 r--p 00014000 ca:02 16818313                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fad02fc2000-7fad02fc3000 rw-p 00015000 ca:02 16818313                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7fad02fc3000-7fad02fc5000 r-xp 00000000 ca:02 42510226                   /usr/local/lib/ruby/gems/2.1.0/gems/extreme_timeout-0.3.1/lib/extreme_timeout.so
7fad02fc5000-7fad031c4000 ---p 00002000 ca:02 42510226                   /usr/local/lib/ruby/gems/2.1.0/gems/extreme_timeout-0.3.1/lib/extreme_timeout.so
7fad031c4000-7fad031c5000 r--p 00001000 ca:02 42510226                   /usr/local/lib/ruby/gems/2.1.0/gems/extreme_timeout-0.3.1/lib/extreme_timeout.so
7fad031c5000-7fad031c6000 rw-p 00002000 ca:02 42510226                   /usr/local/lib/ruby/gems/2.1.0/gems/extreme_timeout-0.3.1/lib/extreme_timeout.so
7fad031c6000-7fad031c8000 rw-p 00000000 00:00 0
7fad031c8000-7fad031ed000 r-xp 00000000 ca:02 16827352                   /usr/lib64/libtinfo.so.5.9
7fad031ed000-7fad033ed000 ---p 00025000 ca:02 16827352                   /usr/lib64/libtinfo.so.5.9
7fad033ed000-7fad033f1000 r--p 00025000 ca:02 16827352                   /usr/lib64/libtinfo.so.5.9
7fad033f1000-7fad033f2000 rw-p 00029000 ca:02 16827352                   /usr/lib64/libtinfo.so.5.9
7fad033f2000-7fad03418000 r-xp 00000000 ca:02 16827342                   /usr/lib64/libncurses.so.5.9
7fad03418000-7fad03617000 ---p 00026000 ca:02 16827342                   /usr/lib64/libncurses.so.5.9
7fad03617000-7fad03618000 r--p 00025000 ca:02 16827342                   /usr/lib64/libncurses.so.5.9
7fad03618000-7fad03619000 rw-p 00026000 ca:02 16827342                   /usr/lib64/libncurses.so.5.9
7fad03619000-7fad03655000 r-xp 00000000 ca:02 16922576                   /usr/lib64/libreadline.so.6.2
7fad03655000-7fad03855000 ---p 0003c000 ca:02 16922576                   /usr/lib64/libreadline.so.6.2
7fad03855000-7fad03857000 r--p 0003c000 ca:02 16922576                   /usr/lib64/libreadline.so.6.2
7fad03857000-7fad0385d000 rw-p 0003e000 ca:02 16922576                   /usr/lib64/libreadline.so.6.2
7fad0385d000-7fad0385f000 rw-p 00000000 00:00 0
7fad0385f000-7fad03866000 r-xp 00000000 ca:02 991155                     /usr/local/lib/ruby/2.1.0/x86_64-linux/readline.so
7fad03866000-7fad03a66000 ---p 00007000 ca:02 991155                     /usr/local/lib/ruby/2.1.0/x86_64-linux/readline.so
7fad03a66000-7fad03a67000 r--p 00007000 ca:02 991155                     /usr/local/lib/ruby/2.1.0/x86_64-linux/readline.so
7fad03a67000-7fad03a68000 rw-p 00008000 ca:02 991155                     /usr/local/lib/ruby/2.1.0/x86_64-linux/readline.so
7fad03a68000-7fad03a70000 r-xp 00000000 ca:02 991159                     /usr/local/lib/ruby/2.1.0/x86_64-linux/stringio.so
7fad03a70000-7fad03c6f000 ---p 00008000 ca:02 991159                     /usr/local/lib/ruby/2.1.0/x86_64-linux/stringio.so
7fad03c6f000-7fad03c70000 r--p 00007000 ca:02 991159                     /usr/local/lib/ruby/2.1.0/x86_64-linux/stringio.so
7fad03c70000-7fad03c71000 rw-p 00008000 ca:02 991159                     /usr/local/lib/ruby/2.1.0/x86_64-linux/stringio.so
7fad03c71000-7fad03c74000 r-xp 00000000 ca:02 991162                     /usr/local/lib/ruby/2.1.0/x86_64-linux/thread.so
7fad03c74000-7fad03e73000 ---p 00003000 ca:02 991162                     /usr/local/lib/ruby/2.1.0/x86_64-linux/thread.so
7fad03e73000-7fad03e74000 r--p 00002000 ca:02 991162                     /usr/local/lib/ruby/2.1.0/x86_64-linux/thread.so
7fad03e74000-7fad03e75000 rw-p 00003000 ca:02 991162                     /usr/local/lib/ruby/2.1.0/x86_64-linux/thread.so
7fad03e75000-7fad03e77000 r-xp 00000000 ca:02 33836157                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
7fad03e77000-7fad04077000 ---p 00002000 ca:02 33836157                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
7fad04077000-7fad04078000 r--p 00002000 ca:02 33836157                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
7fad04078000-7fad04079000 rw-p 00003000 ca:02 33836157                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
7fad04079000-7fad0407b000 r-xp 00000000 ca:02 26564563                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
7fad0407b000-7fad0427a000 ---p 00002000 ca:02 26564563                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
7fad0427a000-7fad0427b000 r--p 00001000 ca:02 26564563                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
7fad0427b000-7fad0427c000 rw-p 00002000 ca:02 26564563                   /usr/local/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
7fad0427c000-7fad0a7a3000 r--p 00000000 ca:02 8396121                    /usr/lib/locale/locale-archive
7fad0a7a3000-7fad0a7a5000 r-xp 00000000 ca:02 16819245                   /usr/lib64/libfreebl3.so
7fad0a7a5000-7fad0a9a4000 ---p 00002000 ca:02 16819245                   /usr/lib64/libfreebl3.so
7fad0a9a4000-7fad0a9a5000 r--p 00001000 ca:02 16819245                   /usr/lib64/libfreebl3.so
7fad0a9a5000-7fad0a9a6000 rw-p 00002000 ca:02 16819245                   /usr/lib64/libfreebl3.so
7fad0a9a6000-7fad0ab5d000 r-xp 00000000 ca:02 16819247                   /usr/lib64/libc-2.17.so
7fad0ab5d000-7fad0ad5d000 ---p 001b7000 ca:02 16819247                   /usr/lib64/libc-2.17.so
7fad0ad5d000-7fad0ad61000 r--p 001b7000 ca:02 16819247                   /usr/lib64/libc-2.17.so
7fad0ad61000-7fad0ad63000 rw-p 001bb000 ca:02 16819247                   /usr/lib64/libc-2.17.so
7fad0ad63000-7fad0ad68000 rw-p 00000000 00:00 0
7fad0ad68000-7fad0ae69000 r-xp 00000000 ca:02 16826953                   /usr/lib64/libm-2.17.so
7fad0ae69000-7fad0b068000 ---p 00101000 ca:02 16826953                   /usr/lib64/libm-2.17.so
7fad0b068000-7fad0b069000 r--p 00100000 ca:02 16826953                   /usr/lib64/libm-2.17.so
7fad0b069000-7fad0b06a000 rw-p 00101000 ca:02 16826953                   /usr/lib64/libm-2.17.so
7fad0b06a000-7fad0b072000 r-xp 00000000 ca:02 16826948                   /usr/lib64/libcrypt-2.17.so
7fad0b072000-7fad0b271000 ---p 00008000 ca:02 16826948                   /usr/lib64/libcrypt-2.17.so
7fad0b271000-7fad0b272000 r--p 00007000 ca:02 16826948                   /usr/lib64/libcrypt-2.17.so
7fad0b272000-7fad0b273000 rw-p 00008000 ca:02 16826948                   /usr/lib64/libcrypt-2.17.so
7fad0b273000-7fad0b2a1000 rw-p 00000000 00:00 0
7fad0b2a1000-7fad0b2a4000 r-xp 00000000 ca:02 16826950                   /usr/lib64/libdl-2.17.so
7fad0b2a4000-7fad0b4a3000 ---p 00003000 ca:02 16826950                   /usr/lib64/libdl-2.17.so
7fad0b4a3000-7fad0b4a4000 r--p 00002000 ca:02 16826950                   /usr/lib64/libdl-2.17.so
7fad0b4a4000-7fad0b4a5000 rw-p 00003000 ca:02 16826950                   /usr/lib64/libdl-2.17.so
7fad0b4a5000-7fad0b4bb000 r-xp 00000000 ca:02 17592103                   /usr/lib64/libpthread-2.17.so
7fad0b4bb000-7fad0b6bb000 ---p 00016000 ca:02 17592103                   /usr/lib64/libpthread-2.17.so
7fad0b6bb000-7fad0b6bc000 r--p 00016000 ca:02 17592103                   /usr/lib64/libpthread-2.17.so
7fad0b6bc000-7fad0b6bd000 rw-p 00017000 ca:02 17592103                   /usr/lib64/libpthread-2.17.so
7fad0b6bd000-7fad0b6c1000 rw-p 00000000 00:00 0
7fad0b6c1000-7fad0b96f000 r-xp 00000000 ca:02 358591                     /usr/local/lib/libruby.so.2.1.0
7fad0b96f000-7fad0bb6f000 ---p 002ae000 ca:02 358591                     /usr/local/lib/libruby.so.2.1.0
7fad0bb6f000-7fad0bb74000 r--p 002ae000 ca:02 358591                     /usr/local/lib/libruby.so.2.1.0
7fad0bb74000-7fad0bb78000 rw-p 002b3000 ca:02 358591                     /usr/local/lib/libruby.so.2.1.0
7fad0bb78000-7fad0bb9d000 rw-p 00000000 00:00 0
7fad0bb9d000-7fad0bbbe000 r-xp 00000000 ca:02 16890018                   /usr/lib64/ld-2.17.so
7fad0bca7000-7fad0bcae000 r--s 00000000 ca:02 16827292                   /usr/lib64/gconv/gconv-modules.cache
7fad0bcae000-7fad0bdb4000 rw-p 00000000 00:00 0
7fad0bdb7000-7fad0bdb9000 rw-p 00000000 00:00 0
7fad0bdb9000-7fad0bdba000 ---p 00000000 00:00 0
7fad0bdba000-7fad0bdbe000 rw-p 00000000 00:00 0                          [stack:10596]
7fad0bdbe000-7fad0bdbf000 r--p 00021000 ca:02 16890018                   /usr/lib64/ld-2.17.so
7fad0bdbf000-7fad0bdc0000 rw-p 00022000 ca:02 16890018                   /usr/lib64/ld-2.17.so
7fad0bdc0000-7fad0bdc1000 rw-p 00000000 00:00 0
7fff8da65000-7fff8e264000 rw-p 00000000 00:00 0
7fff8e3e8000-7fff8e3ea000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

**Comment by yasaichi** [comment]
When I changed the OS to Ubuntu 14.04 LTS, it was fixed.
